### ISSUE TITLE
Design "endcap" architecture

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#120]
ActivityPub Sharp is intended to expose multiple tiers of APIs. The lowest-level API is the raw parsers and models available in the Types package, and the mid-level API consists of use cases that will be defined in #117. This story is to create the high-level architecture, which is a pair of "endcap" packages which bring together the most important use cases into a unified entry point.

The first endcap package will be for client usage. Part of it, `IActivityPubClient`, has already been created. These additional features must be designed as well:
* [ ] Per-server client
* [ ] Stateful client
* [ ] Navigational API (smart entities, basically)

The other endcap is for servers. The purpose here is to provide a single entry point to process an incoming request
* [ ] ActivityPub server - processes arbitrary objects
* [ ] HTTP server - processes HTTP requests (through an abstraction)

Everything here is a long-term goal, the last stage of the project really. But we need to work out the vision now since everything else will be building to this.
