### ISSUE TITLE
Set up repository, tooling, and project management

### ISSUE THREAD

**Issue by warriordog** [warriordog/ActivityPubSharp#3]
All the DevOps-y parts of OSS. Configure the github repo, create a build pipeline, establish contributor guidelines and technical standards, etc.

**Phase 1 - Groundwork:**

- [ ] Create standard issue labels
- [ ] Establish documentation standards
- [ ] Define testing standards

**Phase 2 - MVP:**

- [ ] Enable security checks
- [ ] Enable Dependabot updates
- [ ] Create build pipeline

**Phase 3 - Best Practices:**

- [ ] Create issue template
- [ ] Create PR template
- [ ] Publish releases from pipeline
- [ ] Code checks on PR (github actions?)

**Phase 4 - Nice to Have:**

- [ ] Set up Projects area
- [ ] Set up Wiki area
